// expo config plugin for react-native-voip-push-notification.
//
// the library ships JS bindings + Objective-C native module but no expo
// plugin and no AppDelegate auto-wiring. without the AppDelegate setup,
// iOS never asks apple for a voip token and the JS register event fires
// with an empty string.
//
// what this plugin does:
//   1. patches AppDelegate.swift:
//      - import PushKit
//      - call RNVoipPushNotificationManager.voipRegistration() on launch
//      - conform to PKPushRegistryDelegate via an extension, forwarding the
//        three delegate methods into RNVoipPushNotificationManager
//   2. creates a bridging header that imports RNVoipPushNotificationManager.h
//      so Swift can see the Objective-C class (the library's podspec doesn't
//      define a swift module so `import RNVoipPushNotification` doesn't work)
//   3. wires SWIFT_OBJC_BRIDGING_HEADER into the Xcode project's build
//      settings so the bridging header is actually consulted at compile time
//
// to use: add "./plugins/withVoipPushNotification" to app.json's plugins array.

const {
  withAppDelegate,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const PUSHKIT_IMPORT = "import PushKit";
const VOIP_REGISTRATION_CALL = "RNVoipPushNotificationManager.voipRegistration()";
const EXTENSION_MARKER = "// VoIP push delegate (added by withVoipPushNotification)";

const VOIP_EXTENSION = `

${EXTENSION_MARKER}
extension AppDelegate: PKPushRegistryDelegate {
  public func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
    RNVoipPushNotificationManager.didUpdate(pushCredentials, forType: type.rawValue)
  }

  public func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
    // no action required
  }

  public func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
    let uuid = (payload.dictionaryPayload["uuid"] as? String) ?? UUID().uuidString
    RNVoipPushNotificationManager.addCompletionHandler(uuid, completionHandler: completion)
    RNVoipPushNotificationManager.didReceiveIncomingPush(with: payload, forType: type.rawValue)
    completion()
  }
}
`;

const BRIDGING_HEADER_BASENAME = "RNVoipPushNotification-Bridging-Header.h";
const BRIDGING_HEADER_CONTENT = `// auto-generated by ./plugins/withVoipPushNotification.js.
// makes RNVoipPushNotificationManager (Objective-C) visible to AppDelegate.swift.
// the library's podspec doesn't define a Swift module, so a bridging header is
// the only way to import the class into Swift.

#import "RNVoipPushNotificationManager.h"
`;

function insertAfterLastImport(source, line) {
  if (source.includes(line)) return source;
  const importRegex = /^(import\s+\w+)$/gm;
  const matches = [...source.matchAll(importRegex)];
  if (matches.length > 0) {
    const lastImport = matches[matches.length - 1];
    const insertIndex = lastImport.index + lastImport[0].length;
    return source.slice(0, insertIndex) + "\n" + line + source.slice(insertIndex);
  }
  return line + "\n" + source;
}

function patchAppDelegate(source) {
  let out = source;

  // 1. PushKit import.
  out = insertAfterLastImport(out, PUSHKIT_IMPORT);

  // 2. fire voipRegistration() inside the launch handler. expo SDK 53+
  //    AppDelegate has `func application(_ application: UIApplication,
  //    didFinishLaunchingWithOptions ...)`. inserting at the top of the body
  //    so registration kicks off before the JS bridge boots (required for
  //    cold-launch voip push delivery within apple's 5s budget).
  if (!out.includes(VOIP_REGISTRATION_CALL)) {
    const launchRegex = /(func\s+application\([^)]*didFinishLaunchingWithOptions[^)]*\)[^{]*\{\s*\n)/;
    if (!launchRegex.test(out)) {
      throw new Error(
        "withVoipPushNotification: couldn't find didFinishLaunchingWithOptions in AppDelegate.swift. " +
          "expo SDK structure may have changed — update this plugin's regex.",
      );
    }
    out = out.replace(launchRegex, `$1    ${VOIP_REGISTRATION_CALL}\n`);
  }

  // 3. append the PKPushRegistryDelegate extension at the end of the file.
  //    extensions are isolated and trivial to remove if we ever swap libraries.
  if (!out.includes(EXTENSION_MARKER)) {
    out = out.trimEnd() + VOIP_EXTENSION;
  }

  return out;
}

const withAppDelegatePatch = (config) =>
  withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withVoipPushNotification: expected Swift AppDelegate, got ${config.modResults.language}. ` +
          "this plugin only supports expo SDK 53+ where AppDelegate is .swift.",
      );
    }
    config.modResults.contents = patchAppDelegate(config.modResults.contents);
    return config;
  });

const withBridgingHeaderFile = (config) =>
  withDangerousMod(config, [
    "ios",
    async (config) => {
      const { platformProjectRoot, projectName } = config.modRequest;
      if (!projectName) {
        throw new Error("withVoipPushNotification: projectName missing from modRequest");
      }
      const targetFolder = path.join(platformProjectRoot, projectName);
      if (!fs.existsSync(targetFolder)) {
        throw new Error(
          `withVoipPushNotification: ${targetFolder} doesn't exist. prebuild may not have created the iOS target folder.`,
        );
      }
      const headerPath = path.join(targetFolder, BRIDGING_HEADER_BASENAME);
      fs.writeFileSync(headerPath, BRIDGING_HEADER_CONTENT, "utf8");
      return config;
    },
  ]);

const withBridgingHeaderBuildSetting = (config) =>
  withXcodeProject(config, (config) => {
    const projectName = config.modRequest.projectName;
    if (!projectName) {
      throw new Error("withVoipPushNotification: projectName missing for xcode mod");
    }
    const bridgingHeaderRef = `${projectName}/${BRIDGING_HEADER_BASENAME}`;

    const xcodeProject = config.modResults;
    const configurations = xcodeProject.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const buildSettings = configurations[key] && configurations[key].buildSettings;
      // only touch app-target configurations, not pod/aggregate ones — those have
      // PRODUCT_NAME set. pods don't.
      if (buildSettings && buildSettings.PRODUCT_NAME) {
        buildSettings.SWIFT_OBJC_BRIDGING_HEADER = `"${bridgingHeaderRef}"`;
      }
    }
    return config;
  });

// without `aps-environment` in the entitlements, iOS silently returns an empty
// voip device token. expo-notifications would set this automatically, but
// donna uses raw react-native-voip-push-notification + apns so we add it here.
// "development" is right for dev builds (sandbox APNs). switches to "production"
// at the same time APNS_PRODUCTION flips in the backend env — coordinate the
// two when going to testflight/store.
const withApsEnvironment = (config) =>
  withEntitlementsPlist(config, (config) => {
    config.modResults["aps-environment"] = "development";
    return config;
  });

const withVoipPushNotification = (config) => {
  config = withApsEnvironment(config);
  config = withAppDelegatePatch(config);
  config = withBridgingHeaderFile(config);
  config = withBridgingHeaderBuildSetting(config);
  return config;
};

module.exports = withVoipPushNotification;
