// expo config plugin for react-native-voip-push-notification.
// the library itself ships only the JS bindings + Objective-C native module —
// no expo plugin and no AppDelegate auto-wiring. without the AppDelegate
// wiring, iOS never asks apple for a voip token and the JS register event
// fires with an empty string. this plugin patches AppDelegate.swift to:
//   1. import PushKit
//   2. call RNVoipPushNotificationManager.voipRegistration() on launch
//   3. conform to PKPushRegistryDelegate via an extension and forward the
//      three delegate methods (credentials update, invalid token, push received)
//      into RNVoipPushNotificationManager's class methods.
//
// expo SDK 53+ AppDelegate is Swift. RNVoipPushNotificationManager is
// Objective-C; it's exposed to Swift automatically via the umbrella header
// generated by the library's podspec — no bridging header needed.
//
// to use: add "./plugins/withVoipPushNotification" to app.json's plugins array.

const { withAppDelegate } = require("@expo/config-plugins");

const PUSHKIT_IMPORT = "import PushKit";
const VOIP_REGISTRATION_CALL = "RNVoipPushNotificationManager.voipRegistration()";
const EXTENSION_MARKER = "// VoIP push delegate (added by withVoipPushNotification)";

const VOIP_EXTENSION = `

${EXTENSION_MARKER}
extension AppDelegate: PKPushRegistryDelegate {
  public func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
    RNVoipPushNotificationManager.didUpdate(pushCredentials, forType: type.rawValue)
  }

  public func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
    // no action required
  }

  public func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
    let uuid = (payload.dictionaryPayload["uuid"] as? String) ?? UUID().uuidString
    RNVoipPushNotificationManager.addCompletionHandler(uuid, completionHandler: completion)
    RNVoipPushNotificationManager.didReceiveIncomingPush(with: payload, forType: type.rawValue)
    completion()
  }
}
`;

function patchAppDelegate(source) {
  let out = source;

  // 1. add PushKit import. place it right after the last existing top-level
  //    import line so the file stays organized.
  if (!out.includes(PUSHKIT_IMPORT)) {
    const importRegex = /^(import\s+\w+)$/gm;
    const matches = [...out.matchAll(importRegex)];
    if (matches.length > 0) {
      const lastImport = matches[matches.length - 1];
      const insertIndex = lastImport.index + lastImport[0].length;
      out = out.slice(0, insertIndex) + "\n" + PUSHKIT_IMPORT + out.slice(insertIndex);
    } else {
      // no imports? prepend.
      out = PUSHKIT_IMPORT + "\n" + out;
    }
  }

  // 2. call voipRegistration() inside the launch handler. expo SDK 53+ AppDelegate
  //    has `func application(_ application: UIApplication, didFinishLaunchingWithOptions ...)`.
  //    we insert at the top of the function body so registration kicks off before
  //    the JS bridge boots — required for cold-launch voip push delivery.
  if (!out.includes(VOIP_REGISTRATION_CALL)) {
    const launchRegex = /(func\s+application\([^)]*didFinishLaunchingWithOptions[^)]*\)[^{]*\{\s*\n)/;
    if (launchRegex.test(out)) {
      out = out.replace(
        launchRegex,
        `$1    ${VOIP_REGISTRATION_CALL}\n`,
      );
    } else {
      throw new Error(
        "withVoipPushNotification: couldn't find didFinishLaunchingWithOptions in AppDelegate.swift. " +
          "expo SDK structure may have changed — update this plugin's regex.",
      );
    }
  }

  // 3. append the PKPushRegistryDelegate extension at the end of the file.
  //    using an extension instead of modifying the class declaration keeps
  //    the patch isolated and easy to remove.
  if (!out.includes(EXTENSION_MARKER)) {
    out = out.trimEnd() + VOIP_EXTENSION;
  }

  return out;
}

const withVoipPushNotification = (config) => {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withVoipPushNotification: expected Swift AppDelegate, got ${config.modResults.language}. ` +
          "this plugin only supports expo SDK 53+ where AppDelegate is .swift.",
      );
    }
    config.modResults.contents = patchAppDelegate(config.modResults.contents);
    return config;
  });
};

module.exports = withVoipPushNotification;
