import { useRouter } from "expo-router";
import { OnboardingShell } from "@/components/OnboardingShell";

/**
 * the wow page. four serif paragraphs donna writes about the user from
 * ingested data. placeholder shows where the prose lives; the brain
 * generates the real content in a later pr.
 */
export default function Reveal() {
  const router = useRouter();
  return (
    <OnboardingShell
      eyebrow="what i learned"
      title="you."
      body="placeholder — four serif paragraphs generated by claude from ingested gmail + calendar + chat data. identity, people, what's hanging, patterns. tap-to-edit per paragraph in the real version."
      primaryLabel="all good"
      onPrimary={() => router.push("/onboarding/demo")}
      secondaryLabel="fix something"
      onSecondary={() => router.push("/onboarding/demo")}
    />
  );
}
